export const languagesData = [
    "English - (US)",
    "English - (UK)",
    "Hindi - (India)",
    "Spanish - (Spain)",
    "Spanish - (Latin America)",
    "French - (France)",
    "French - (Canada)",
    "German - (Germany)",
    "Chinese - (Simplified)",
    "Chinese - (Traditional)",
    "Japanese - (Japan)",
    "Korean - (South Korea)",
    "Portuguese - (Portugal)",
    "Portuguese - (Brazil)",
    "Russian - (Russia)",
    "Italian - (Italy)",
    "Arabic - (Saudi Arabia)",
    "Arabic - (Egypt)",
    "Dutch - (Netherlands)",
    "Turkish - (Turkey)",
    "Swedish - (Sweden)",
    "Danish - (Denmark)",
    "Norwegian - (Norway)",
    "Finnish - (Finland)",
    "Greek - (Greece)",
    "Polish - (Poland)",
    "Czech - (Czech Republic)",
    "Hungarian - (Hungary)",
    "Romanian - (Romania)",
    "Hebrew - (Israel)",
    "Thai - (Thailand)",
    "Indonesian - (Indonesia)",
    "Malay - (Malaysia)",
    "Vietnamese - (Vietnam)",
    "Filipino - (Philippines)",
    "Ukrainian - (Ukraine)",
    "Bengali - (Bangladesh)",
    "Tamil - (India)",
    "Telugu - (India)",
    "Marathi - (India)",
    "Gujarati - (India)",
    "Punjabi - (India)",
    "Kannada - (India)",
    "Malayalam - (India)",
    "Swahili - (Kenya)",
    "Amharic - (Ethiopia)",
    "Afrikaans - (South Africa)",
    "Pashto - (Afghanistan)",
    "Farsi - (Iran)",
    "Serbian - (Serbia)",
    "Croatian - (Croatia)",
    "Slovak - (Slovakia)",
    "Bulgarian - (Bulgaria)",
    "Lithuanian - (Lithuania)",
    "Latvian - (Latvia)",
    "Estonian - (Estonia)",
  ];