export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAILURE = "FETCH_CURRENT_USER_FAILURE";

export const FETCH_FEED_USERS = "FETCH_FEED_USERS";
export const FETCH_FEED_USERS_SUCCESS = "FETCH_FEED_USERS_SUCCESS";
export const FETCH_FEED_USERS_FAILURE = "FETCH_FEED_USERS_FAILURE";

export const FETCH_FEED2_USERS = "FETCH_FEED2_USERS";
export const FETCH_FEED2_USERS_SUCCESS = "FETCH_FEED2_USERS_SUCCESS";
export const FETCH_FEED2_USERS_FAILURE = "FETCH_FEED2_USERS_FAILURE";

export const FETCH_FEED_MESSAGES = "FETCH_FEED_MESSAGES";
export const FETCH_FEED_MESSAGES_SUCCESS = "FETCH_FEED_MESSAGES_SUCCESS";
export const FETCH_FEED_MESSAGES_FAILURE = "FETCH_FEED_MESSAGES_FAILURE";

export const FETCH_FEED_CHAT_ROOMS = "FETCH_FEED_CHAT_ROOMS";
export const FETCH_FEED_CHAT_ROOMS_SUCCESS = "FETCH_FEED_CHAT_ROOMS_SUCCESS";
export const FETCH_FEED_CHAT_ROOMS_FAILURE = "FETCH_FEED_CHAT_ROOMS_FAILURE";

export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const UPDATE_CURRENT_USER_SUCCESS = "UPDATE_CURRENT_USER_SUCCESS";
export const UPDATE_CURRENT_USER_FAILURE = "UPDATE_CURRENT_USER_FAILURE";

export const UPDATE_FEED_USER = "UPDATE_FEED_USER";
export const UPDATE_FEED_USER_SUCCESS = "UPDATE_FEED_USER_SUCCESS";
export const UPDATE_FEED_USER_FAILURE = "UPDATE_FEED_USER_FAILURE";

export const UPDATE_USER_STATE = "UPDATE_USER_STATE";
